"""banco_v1

Revision ID: 1335b6d9c96b
Revises: 
Create Date: 2022-12-07 03:04:22.048944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1335b6d9c96b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_criacao', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=False),
    sa.Column('separador', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_criacao', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('INTEGER', 'FLOAT', 'STRING', 'DATE', 'BOOLEAN', name='tipocampo'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_criacao', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fonte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dt_criacao', sa.Date(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('site', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fonte')
    op.drop_table('dado')
    op.drop_table('campo')
    op.drop_table('arquivo')
    # ### end Alembic commands ###
